### PR TITLE
Adding the configure_linux.sh script

### PR DESCRIPTION
**Pull request by tchoulihan**
For issue #19 
@gubatron @aldenml

### CODE REVIEW

**Comment by tchoulihan** [comment]
IMO we should just combine them, so that ./build_linux would have everything.

**Comment by gubatron** [comment]
If you combined this into `build_linux.sh`, you'd have to make the script interactive or include a parameter like `--configure`, as you do this step only once, or whenever library dependencies are updated.

**Comment by gubatron** [comment]
I rather have multiple lego blocks and build as necessary. :)

**Comment by tchoulihan** [comment]
You only build the .so file once as well, correct? Once you have it you don't need to build it again, unless one of those dependencies changes, in which case you have to start from scratch anyway.

**Comment by gubatron** [comment]
#thoughts

I'm thinking we could have another common script to not repeat ourselves when it comes to defining paths and version numbers, something like `env_linux.sh`

and we could `source` that script at the start of the other two.

>You only build the .so file once as well, correct? Once you have it you don't need to build it again, unless one of those dependencies changes, in which case you have to start from scratch anyway.

the final .so can get built several times, without having to build libtorrent. As changes on libtorrent.i tend to happen frequently.

**Comment by gubatron** [comment]
oh, forgot to ask you to put this on a separate branch so we could both work on it before mergin the final script to master.

**Comment by tchoulihan** [comment]
Which branch would you like it on?

**Comment by gubatron** [comment]
```
git checkout -b linux-configure
```

and send another PR from there.

**Comment by tchoulihan** [comment]
> I'm thinking we could have another common script to not repeat ourselves when it comes to defining paths and version numbers, something like env_linux.sh

I agree with this, it is kind of redundant as it is. These have to be `export` vars, rather than simple shell script vars, correct?

**Comment by tchoulihan** [comment]
Also, I'm not seeing the new branch yet. I just see master and libtorrent-trunk

**Comment by gubatron** [comment]
`export` vars are good to me.

Make sure to check out from `master` your new branch.

**Comment by gubatron** [comment]
you can push to your own repo like this:

if you remote `origin` is `https://github.com/tchoulihan/frostwire-jlibtorrent`

```
git checkout -b linux-configure
git push origin linux-configure
```

then create PR from github

**Comment by gubatron** [comment]
(The way I work is that I have the original repo as `origin`, and my own repo as `gubatron`,
so in your case you could have things like this:

`git remote add origin https://github.com/frostwire/frostwire-jlibtorrent`
`git remote add tchoulihan https://github.com/tchoulihan/frostwire-jlibtorrent`

and my last instructions would be instead

```
git checkout -b linux-configure
git push tchoulihan linux-configure
```

your new branch would be visible on your github fork, from which you'd send the PR.
Then I could send you patches to that branch until we're done.
)

**Comment by tchoulihan** [comment]
I don't follow you. That just basically renames my branch. I still need one on frostwire to submit a pull request to. Right now, only master and libtrunk are available.

**Comment by gubatron** [comment]
can you type:

`git remote -v` and paste the output here

**Comment by tchoulihan** [comment]
```
origin	https://github.com/tchoulihan/frostwire-jlibtorrent.git (fetch)
origin	https://github.com/tchoulihan/frostwire-jlibtorrent.git (push)
```

**Comment by gubatron** [comment]
ok, let's start by doing this:

```
git remote rename origin tchoulihan
git remote add origin https://github.com/frostwire/frostwire-jlibtorrent
```

That way you have the two remotes, and you can easily sync the latest changes from the original repo into your fork.

**Comment by gubatron** [comment]
then, go to your `master` branch (for sanity)

`git checkout master`

and do a `git log` and show me the latest couple of entries, we should see at the top

>Adding the configure_linux.sh script

**Comment by tchoulihan** [comment]
Yes I do see that.

**Comment by gubatron** [comment]
perfect, now we'll create a new branch out of this state.

`git checkout -b linux-configure`

then do another `git log` and we should still see the same entry:

>Adding the configure_linux.sh script

**Comment by tchoulihan** [comment]
Yep its there.

**Comment by gubatron** [comment]
`git branch` should show that you're now standing on `linux-configure`.

Now we want to push this new branch to your `frostwire-jlibtorrent` on github.

`git push tchoulihan linux-configure`

**Comment by tchoulihan** [comment]
Yep did that push.

**Comment by gubatron** [comment]
ok, now send another PR, so we can close this one, and I can checkout your branch to work locally on it.

**Comment by tchoulihan** [comment]
So you want me to submit it to frostwire:master?

**Comment by tchoulihan** [comment]
If you don't want to actually push another branch, you can view and test out any PR locally like this:
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by gubatron** [comment]
oh dude, thanks for that!

**Comment by gubatron** [comment]
if you haven't submitted the branch, then I'll try that.

**Comment by tchoulihan** [comment]
No problem sir. Would you like me to cancel out this pull request, and redo it from my `linux-configure` branch, or continue on with this one?

**Comment by gubatron** [comment]
(checking the instructions on how to do it from the pull request.)

**Comment by gubatron** [comment]
I think I like better the feature branch approach., Please submit a new PR.

**Comment by tchoulihan** [comment]
Okay, in that case I need you to create a branch named frostwire:configure-linux that I can submit the PR to.

**Comment by gubatron** [comment]
nope. all you have to do, is push your new branch to your remote repo, and then from your fork's page, you can submit a new pull request.

**Comment by tchoulihan** [comment]
Okay, I'll just submit it from tchoulihan:configure-linux to frostwire:master, since that's my only option.

**Comment by gubatron** [comment]
I see this one
https://github.com/tchoulihan/frostwire-jlibtorrent/tree/linux-configure

**Comment by tchoulihan** [comment]
Yes but that's on my branch, how would you edit that?

**Comment by gubatron** [comment]
:) You will see.

I'll check it out locally, work on it, and send YOU pull requests.

**Comment by gubatron** [comment]
the other option is you let me write to your repo and I can directly push to your repo, all changes on that branch will be reflected automatically on our Pull Request thread, it's pretty cool.

**Comment by gubatron** [comment]
but let's work it the formal way, that way you can reject shitty PR's from me.

**Comment by tchoulihan** [comment]
Oh gotcha. I've never done that before with projects but its no problem.. The usual way is for me to submit fixes and requests to some dev branches of your project, since you're the maintainer.

**Comment by tchoulihan** [comment]
Its up there anyway, submit any pull requests you like.

**Comment by gubatron** [comment]
this is how projects with thousands of collaborators tend to work as they can't give everyone write access.

**Comment by gubatron** [comment]
on your repo, from the new branch, please click here

screen shot 2015-06-04 at 11 44 48 am

**Pull request closed without merging**
