### PR TITLE
Adding the configure_linux.sh script

### PR DESCRIPTION
**Pull request by tchoulihan**
#19

### CODE REVIEW

**Comment by gubatron** [comment]
sweet, thanks.

**Comment by tchoulihan** [comment]
No problem dude, getting set up is always the hardest part haha.

**Comment by gubatron** [comment]
if you merge my PR to your repo, the merge should automatically appear here.

**Comment by gubatron** [comment]
then I'll send another commit with the common script and any other necessary fixes.

**Comment by gubatron** [comment]
:+1:

**Comment by tchoulihan** [comment]
It might be harder to merge this in now, without reverting the previous commits or resolving the merge conflicts.

**Comment by gubatron** [comment]
don't worry about it, I'm working on it and I'll make it work.

**Comment by tchoulihan** [comment]
cool beans

**Pull request closed without merging**
