### PR TITLE
Added simple-torrent-android to projects section.

### PR DESCRIPTION
**Pull request by masterwok**
I would like to add my library to the "Projects using jLibtorrent" section as I think other people will find it useful.

### CODE REVIEW

**Comment by gubatron** [comment]
That's so cool! Sure thing. Merging.

**Comment by masterwok** [comment]
Thanks! :]

**Comment by gubatron** [comment]
We just tweeted about it @masterwok 
https://twitter.com/frostwire/status/1024790112679297024

You're most welcome to collaborate if there's something that could make your life easier and other clients could use.

**Comment by masterwok** [comment]
Wow, thank you. I really appreciate it. I will keep that in mind!

**Comment by proninyaroslav** [comment]
@masterwok
Goodness, why does everyone choose Kotlin for new projects)?

**Comment by masterwok** [comment]
@proninyaroslav haha in my case, I decided to try it out on this project and fell in love with the expression bodies and extension methods.

**Pull request merged**
